sparkflow:
  target: dev
  outputs:
    duckdb:
      type: duckdb
      path: '../texas_bills.duckdb'
      schema: 'bills'
      extensions:
        - httpfs
        - parquet
      external_root: 'data/curated'
    dev:
      type: bigquery
      method: service-account
      project: txspark
      dataset: tx_leg_bills # Change to your development dataset
      keyfile: "{{ env_var('DBT_KEY') }}"
      threads: 4
      timeout_seconds: 300
      location: US
      priority: interactive
