info:
  LegSess: '892'
  pipeline_name: 'texas_bills'
dev_google_sheets_id: 1mB-wBoFKuu4kS482Yc2FQn6kByDJi6uIgm7l09V_8PQ
sources:
  election_results:
    districts: https://results.texas-election.com/static/data/election/49664/1012/Districted.json
    statewide: https://results.texas-election.com/static/data/election/49664/1012/StateWide.json
    federal: https://results.texas-election.com/static/data/election/49664/1012/Federal.json

